export const es = {
  'helloworld': 'hola mundo!!!',
  'THIS WEBSITE HAS SOUND EFFECTS': 'ESTE SITIO CONTIENE EFECTOS DE SONIDO',
  'CLICK ANYWHERE TO ACCEPT': 'CLICK EN LA PAGINA PARA CONTINUAR',
  'START': 'ENTRAR',
  'INITIALIZING DEVELOPER CORE MODULES...': 'INICIALIZANDO MÓDULOS NÚCLEO DEL DESARROLLADOR...',
  'COMPILING EXPERIENCE TIMELINE...': 'COMPILANDO LÍNEA TEMPORAL DE EXPERIENCIA...',
  'CONNECTING TO KNOWLEDGE DATABASE...': 'CONECTANDO A BASE DE DATOS DE CONOCIMIENTOS...',
  'LOADING SKILL MATRIX...': 'CARGANDO MATRIZ DE HABILIDADES...',
  'BIO-SYNC COMPLETE.': 'SINCRONIZACIÓN BIOLÓGICA COMPLETA.',
  'CAREER': 'TRAYECTORIA',
  'SKILLS': 'HABILIDADES',
  'ABOUT': 'CONTACTO',
  '[LOG: CAREER ANALYSIS — SUBJECT D-095]': '[LOG: ANALISIS DE TRAYECTORIA — SUJETO D-095]',

  "MODULE: EXPERIENCE RECORDS": "MÓDULO: REGISTROS DE EXPERIENCIA",
  "This simulation provides an analytical reconstruction of subject D-231’s professional records, academic conditioning, and behavioral directives. Extracted data is processed through the system’s evaluation core to determine operational stability and response accuracy. Findings contribute to the ongoing assessment of the subject’s technical cognition and adaptive progression.": "Esta simulación ofrece una reconstrucción analítica de los registros profesionales, la formación académica y las directrices conductuales del sujeto D-231. Los datos extraídos son procesados por el núcleo de evaluación del sistema para determinar la estabilidad operativa y la precisión de respuesta. Los resultados contribuyen a la evaluación continua de la cognición técnica y la progresión adaptativa del sujeto.",
  
  "During the GrowForce Project, subject D-095 developed an advanced interface using Astro, GSAP, and TailwindCSS. The system incorporated intricate time and scroll-driven animations and was deployed through Vercel for optimal performance. D-095 implemented a communication layer via Astro Actions and Nodemailer, allowing direct visitor messages to GrowForce’s network. Simultaneously, the subject maintained and refined existing frontends under strict deadlines, exhibiting adaptive efficiency and precision in high-demand visual and communication environments.": "Durante el Proyecto GrowForce, el sujeto D-095 desarrolló una interfaz avanzada utilizando Astro, GSAP y TailwindCSS. El sistema incorporó complejas animaciones dependientes del tiempo y del desplazamiento, y fue desplegado a través de Vercel para un rendimiento óptimo. D-095 implementó una capa de comunicación mediante Astro Actions y Nodemailer, permitiendo el envío directo de mensajes de los visitantes hacia la red corporativa de GrowForce. Paralelamente, el sujeto mantuvo y refinó frontends existentes bajo plazos estrictos, demostrando eficiencia adaptativa y precisión en entornos visuales y comunicacionales de alta exigencia.",
  
  "During the iEscrow Simulation, subject D-095 oversaw the operational development of both the Presale and Staking platforms. The subject engineered the frontend architecture using React, Next.js, and Node.js, establishing secure communication between the visual layer and smart contracts via Hardhat, ethers.js, and Wagmi. For the Staking system, data acquisition from BitQuery was implemented to display daily OHLC metrics of the token in USD, while the Presale platform integrated KYC verification, API endpoints, and Next.js Server Actions with SSR for secure transactional flow. Both systems were constructed from initial deployment protocols, evidencing D-095’s capacity for autonomous system design, cross-layer integration, and high technical precision within blockchain-based infrastructures.": "Durante la Simulación iEscrow, el sujeto D-095 supervisó el desarrollo operativo de las plataformas de Preventa y Staking. El sujeto diseñó la arquitectura del frontend con React, Next.js y Node.js, estableciendo comunicación segura entre la capa visual y los contratos inteligentes mediante Hardhat, ethers.js y Wagmi. En el sistema de Staking se implementó la obtención de datos desde BitQuery para mostrar métricas OHLC diarias del token en USD, mientras que la plataforma de Preventa integró verificación KYC, endpoints API y Server Actions con SSR de Next.js para un flujo transaccional seguro. Ambos sistemas fueron construidos desde los protocolos iniciales, evidenciando la capacidad del sujeto D-095 para el diseño autónomo, la integración entre capas y una alta precisión técnica en infraestructuras blockchain.",
  
  "During the CodeCraft assignment, subject D-095 operated within full stack web and mobile development environments, utilizing React, Next.js, Vue, Angular, and React Native with Expo for cross-platform deployment. The subject collaborated under agile methodologies, contributing to iterative release cycles and coordinated task sprints. Backend systems were structured through Node.js and Express, integrating multiple relational and non-relational databases, including SQL, PostgreSQL, and MongoDB. Throughout the operation, subject D-095 exhibited consistency in delivery precision, adaptability to evolving frameworks, and procedural efficiency across diverse technological ecosystems.": "Durante la asignación en CodeCraft, el sujeto D-095 operó en entornos de desarrollo full stack web y móvil, utilizando React, Next.js, Vue, Angular y React Native con Expo para despliegues multiplataforma. El sujeto colaboró bajo metodologías ágiles, participando en ciclos iterativos de entrega y sprints de tareas coordinadas. Los sistemas backend fueron estructurados con Node.js y Express, integrando múltiples bases de datos relacionales y no relacionales, entre ellas SQL, PostgreSQL y MongoDB. A lo largo de la operación, el sujeto D-095 demostró consistencia en la precisión de entrega, adaptabilidad ante marcos evolutivos y eficiencia procedimental en ecosistemas tecnológicos diversos.",

  "Throughout autonomous experimentation cycles, subject D-095 engineered multiple web and mobile systems designed to refine his operational dexterity across diverse stacks. These constructs include full interface pipelines using React, Next.js, Vue, and Angular, as well as mobile deployments through React Native and Expo. Parallel to this, the subject developed algorithmic utilities, UI micro-frameworks, and specialized tooling for workflow optimization. Each project was executed without external oversight, demonstrating D-095’s capacity for self-directed system design, rapid prototyping, and sustained technical evolution driven by curiosity and long-term methodological refinement.": "A lo largo de ciclos autónomos de experimentación, el sujeto D-095 desarrolló múltiples sistemas web y móviles diseñados para perfeccionar su destreza operativa en diversos entornos tecnológicos. Estos ensamblajes incluyen flujos completos de interfaz usando React, Next.js, Vue y Angular, además de despliegues móviles mediante React Native y Expo. En paralelo, el sujeto creó utilidades algorítmicas, micro-frameworks de interfaz y herramientas especializadas para optimizar flujos de trabajo. Cada proyecto fue ejecutado sin supervisión externa, demostrando la capacidad de D-095 para el diseño autodirigido de sistemas, prototipado rápido y una evolución técnica sostenida impulsada por curiosidad y refinamiento metodológico a largo plazo.",

  "MODULE: COGNITIVE DEVELOPMENT": "MÓDULO: DESARROLLO COGNITIVO",

  "Universidad Nacional Del Oeste": "Universidad Nacional Del Oeste",
  "- Bachelor's degree in computer science -": "- Licenciatura en Ciencias de la Computación -",
  "During this training cycle, the candidate engaged in core protocols covering computational theory, object-oriented principles, and structured software design. The program included extensive work with C, Java, and SQL, reinforcing encapsulation, abstraction, algorithmic complexity, and key design patterns for scalable systems. Exposure to discrete mathematics, database architecture, and systematic problem-solving established a strong foundational layer for real-world development. Subject D-095 demonstrated consistent analytical precision and high adaptability across all monitored sessions.": "Durante este ciclo de entrenamiento, el candidato participó en protocolos centrales enfocados en teoría computacional, principios orientados a objetos y diseño estructurado de software. El programa incluyó trabajo intensivo con C, Java y SQL, reforzando encapsulación, abstracción, complejidad algorítmica y patrones clave de diseño para sistemas escalables. La exposición a matemáticas discretas, arquitectura de bases de datos y resolución sistemática de problemas estableció una base sólida para el desarrollo real. El Sujeto D-095 demostró precisión analítica constante y alta adaptabilidad en todas las sesiones monitoreadas.",

  "Helsinki University": "Helsinki University",
  "- Full Stack Open Course -": "- Curso Full Stack Open -",
  "During this advanced module, the candidate completed a full operational cycle in modern web architecture and end-to-end application design. Training involved intensive work with React, Node.js, Express, MongoDB, and GraphQL, emphasizing asynchronous data flows, API orchestration, and resilient full stack environments. By completing all protocols and exercises, the candidate strengthened mastery of distributed logic, component-driven interfaces, and server-side execution patterns. Subject D-095 maintained high technical precision and rapid assimilation of complex workflows throughout the evaluation period.": "Durante este módulo avanzado, el candidato completó un ciclo operativo en arquitectura web moderna y diseño de aplicaciones de extremo a extremo. El entrenamiento incluyó trabajo intensivo con React, Node.js, Express, MongoDB y GraphQL, enfatizando flujos de datos asincrónicos, orquestación de APIs y entornos full stack resilientes. Al completar todos los protocolos y ejercicios, el candidato fortaleció su dominio de lógica distribuida, interfaces basadas en componentes y patrones de ejecución del lado del servidor. El Sujeto D-095 mantuvo alta precisión técnica y rápida asimilación de flujos complejos durante todo el período de evaluación.",

  "Independent Full Stack Training": "Independent Full Stack Training",
  "- Autonomous Development Protocols -": "- Protocolos de Desarrollo Autónomo -",
  "Throughout this autonomous training sequence, the candidate advanced through practical protocols covering both foundational and advanced layers of modern software engineering. The cycle reinforced core principles of HTML, CSS, and JavaScript, extending into TypeScript, React, Vue, Angular, and backend work with Node.js and Express. Additional modules included databases such as MySQL and Transact-SQL, plus essential design patterns. Subject D-095 demonstrated strong discipline, rapid assimilation, and consistent performance.": "A lo largo de esta secuencia de entrenamiento autónomo, el candidato avanzó mediante protocolos prácticos que cubren capas fundamentales y avanzadas de la ingeniería de software moderna. El ciclo reforzó principios esenciales de HTML, CSS y JavaScript, extendiéndose hacia TypeScript, React, Vue, Angular y trabajo backend con Node.js y Express. Módulos adicionales incluyeron bases de datos como MySQL y Transact-SQL, junto con patrones esenciales de diseño. El Sujeto D-095 demostró fuerte disciplina, rápida asimilación y desempeño constante.",

  "IPI": "IPI",
  "- Office Automation Course -": "- Curso de Ofimática -",
  "The subject completed a structured Office Automation Training Program focused on PC operation and the Microsoft Office suite. Throughout the course, the subject manipulated digital environments with precision, mastering data processing, document engineering, and structured information workflows. Under controlled conditions, they demonstrated proficiency in Word, Excel, PowerPoint, and system navigation. The program emphasized operational efficiency, procedural accuracy, and the ability to synthesize information into functional outputs, preparing the subject for high-reliability computational tasks.": "El sujeto completó un Programa Estructurado de Capacitación en Ofimática centrado en operación de PC y el conjunto Microsoft Office. Durante el curso, el sujeto manipuló entornos digitales con precisión, dominando procesamiento de datos, ingeniería documental y flujos estructurados de información. Bajo condiciones controladas, demostró competencia en Word, Excel, PowerPoint y navegación del sistema. El programa enfatizó eficiencia operativa, precisión procedimental y la capacidad de sintetizar información en resultados funcionales, preparando al sujeto para tareas computacionales de alta fiabilidad.",
  
  "MODULE: OPERATIONAL PHILOSOPHY": "MÓDULO: FILOSOFÍA OPERACIONAL",

  "In current operational records, D-095 is identified as an engineer driven by disciplined curiosity and affinity for well-structured workflows. Though accustomed to defined roles, he demonstrates notable adaptability, calibrating his methods under high-pressure conditions while preserving strong standards of code quality whenever mission timing allows.": "En los registros operativos actuales, D-095 es identificado como un ingeniero guiado por curiosidad disciplinada y afinidad por flujos de trabajo bien estructurados. Aunque habituado a roles definidos, demuestra notable adaptabilidad, ajustando sus métodos bajo condiciones de alta presión mientras mantiene fuertes estándares de calidad de código siempre que el tiempo de misión lo permite.",
  "Across multiple learning cycles, D-095 displays a persistent expansion of technical range, integrating new tools with unusual efficiency. His reliance on generative AI functions as an auxiliary processor, accelerating comprehension and solution-building. Evaluators note his ability to convert complex systems into clear, accessible explanations that strengthen team alignment.": "A través de múltiples ciclos de aprendizaje, D-095 muestra una expansión constante de rango técnico, integrando nuevas herramientas con eficiencia inusual. Su uso de IA generativa actúa como un procesador auxiliar, acelerando la comprensión y la creación de soluciones. Los evaluadores señalan su capacidad para convertir sistemas complejos en explicaciones claras y accesibles que fortalecen la alineación del equipo.",
  "Behavioral scans show that D-095 operates from a stable ethical lattice grounded in humility, respect, and tolerance. He engages proactively in communication loops, ensuring shared clarity of objectives and reducing operational drift. Analysts report that this consistent initiative enhances cohesion, positioning him as both a dependable technician and a stabilizing presence within collaborative units.": "Los escaneos conductuales muestran que D-095 opera desde una estructura ética estable basada en humildad, respeto y tolerancia. Participa proactivamente en bucles de comunicación, asegurando claridad compartida de objetivos y reduciendo el desvío operativo. Los analistas informan que esta iniciativa constante refuerza la cohesión, posicionándolo como un técnico confiable y una presencia estabilizadora dentro de unidades colaborativas.",
  "Conclusion: Long-term projections indicate that D-095 will continue refining his methodologies, merging disciplined structure with adaptive insight. His trajectory suggests a constant upward drift in capability, driven by curiosity, ethical stability, and a sustained commitment to elevating every system he becomes part of.": "Conclusión: Las proyecciones a largo plazo indican que D-095 seguirá refinando sus metodologías, fusionando estructura disciplinada con percepción adaptable. Su trayectoria sugiere un avance continuo en capacidad, impulsado por curiosidad, estabilidad ética y un compromiso sostenido por elevar cada sistema del que forma parte.",

  "[LOG: SKILLS ANALYSIS — SUBJECT D-095]": "[LOG: ANÁLISIS DE HABILIDADES — SUJETO D-095]",

  "his segment compiles a procedural breakdown of subject D-095’s verified technical domains and interpersonal attributes. All registered competencies have been processed through automated filtering layers to determine present operational range. The record contributes to continuous monitoring of skill acquisition and cognitive refinement.": "Este segmento reúne un desglose operativo de los dominios técnicos verificados y los rasgos interpersonales del Sujeto D-095. Cada competencia registrada fue procesada mediante capas automáticas de filtrado para definir su rango operativo actual. El informe sostiene el monitoreo continuo de su adquisición de habilidades y refinamiento cognitivo.",

  "Back to Central Node": "Volver al Nodo Central"
}